### ISSUE TITLE
Problem converting csv to yml  file

### ISSUE THREAD

**Issue by saif-analyze** [DOE-police/DOEDA#4]
@ABohynDOE I tried to convert my data file but this what I got in the yaml output. The dataset section is empty and everything went into the response. I will send you the csv file in teams.
```
title: Biological process characterization experiment
run_size: 17
dataset: []
response:
- name: C_Protein,C_Lysine,Duration,pH,Temperature,HCHO:protein,Extent of polymerization
  value:
  - -1,-1,-1,-1,1,0,2.9
  - 1,-1,1,-1,0,-1,14.9
  - 0,0,0,0,0,0,14.4
  - 1,1,0,-1,1,1,27.5
  - 0,0,0,0,0,0,14.6
  - 0,1,-1,-1,-1,-1,3.6
  - -1,1,1,0,1,-1,2.5
  - -1,1,-1,1,0,1,8.5
  - 0,0,0,0,0,0,14.1
  - 1,0,-1,1,1,-1,22
  - -1,0,1,-1,-1,1,4.2
  - 0,0,0,0,0,0,14.2
  - -1,-1,0,1,-1,-1,2.7
  - 0,0,0,0,0,0,15.3
  - 0,-1,1,1,1,1,28.2
  - 1,1,1,1,-1,0,30.7
  - 1,-1,-1,0,-1,1,31.9
  units: null
multilevel: false
doi: 10.1007/s10529-012-1089-y
description: A recently developed class of three-level designs—definitive screening
  designs—was employed to select a quadratic model that describes the effect of six
  input process parameters, including protein concentration, formaldehyde-to-protein
  ratio, lysine concentration, reaction duration, pH, and reaction temperature, on
  a formylation protein-crosslinking reaction.
keywords:
- center-runs
- dsd
- foldover
```

Also this is the code that I ran

```
python csv2json.py --header --no-units --coded --response 1 --title "Biological process characterization experiment" --doi "10.1007/s10529-012-1089-y" --description "A recently developed class of three-level designs—definitive screening designs—was employed to select a quadratic model that describes the effect of six input process parameters, including protein concentration, formaldehyde-to-protein ratio, lysine concentration, reaction duration, pH, and reaction temperature, on a formylation protein-crosslinking reaction." -k center-runs -k dsd -k foldover ../../csv/data_efficient_biological_process_dsd_doeda.csv ../../experiments/biological_process.yaml
```
